Repository ProjectMuseo/Museo, pull requests merged in 2023-11, with the labels that each got.

#54 공지사항 페이지 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/classic/museo/data/AnnouncementDTO.kt
  app/src/main/java/com/classic/museo/itemPage/MypageFragment.kt
  app/src/main/java/com/classic/museo/itemPage/announcement/AnnouncementActivity.kt
  app/src/main/java/com/classic/museo/itemPage/announcement/AnnouncementAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/announcement/AnnouncementDetailActivity.kt
  app/src/main/res/layout/activity_announcement.xml
  app/src/main/res/layout/activity_announcement_detail.xml
  app/src/main/res/layout/announcement_item.xml
Labels: UI, API, DB

#56 [BUG][FEAT](보안상)로그아웃, 로그인 이전 막아놓기, 커뮤니티 수정삭제, 홈 버그 픽스, 카카오 아이디 글 수정 삭제
  .idea/misc.xml
  app/src/main/java/com/classic/museo/Login/LoginActivity.kt
  app/src/main/java/com/classic/museo/MainActivity.kt
  app/src/main/java/com/classic/museo/home/HomeAdapter2.kt
  app/src/main/java/com/classic/museo/home/HomeFragment.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailActivity.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityFragment.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityPlusActivity.kt
  app/src/main/java/com/classic/museo/itemPage/MypageInnerActivity/MypageLogoutDialog.kt
  app/src/main/java/com/classic/museo/itemPage/MypageInnerActivity/MypageWritten.kt
Labels: bug, Feat

#64 [BUG][DB][FEAT]댓글 쓰기, 삭제 기능
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/classic/museo/MainActivity.kt
  app/src/main/java/com/classic/museo/data/CommentDTO.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailActivity.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailDataClass.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailListAdapter.kt
Labels: bug, Feat, DB

#67 [FEAT] : Community 게시글 이미지 추가
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailActivity.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityEditActivity.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityPlusActivity.kt
  app/src/main/res/drawable/community_detail_comment.xml
  app/src/main/res/drawable/community_detail_edit_btn.xml
  app/src/main/res/drawable/community_img_cycle.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_edit.xml
  app/src/main/res/layout/activity_community_plus.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: UI, Feat

#68 [FEAT] : 커뮤니티페이지, 회원가입 및 로그인 일부변경. 상세사항 코멘트 참조
  .idea/misc.xml
  app/src/main/java/com/classic/museo/Login/LoginActivity.kt
  app/src/main/java/com/classic/museo/Login/SignupActivity.kt
  app/src/main/java/com/classic/museo/home/HomeAdapter2.kt
  app/src/main/java/com/classic/museo/home/HomeFragment.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailListAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityFragment.kt
  app/src/main/java/com/classic/museo/itemPage/MypageInnerActivity/MypageLogoutDialog.kt
  app/src/main/java/com/classic/museo/itemPage/MypageInnerActivity/MypageWritten.kt
Labels: Feat, LittleFix

#70 [FEAT] : 비회원 로그인 기능 추가
  app/src/main/java/com/classic/museo/Login/LoginActivity.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailActivity.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityFragment.kt
  app/src/main/java/com/classic/museo/itemPage/MypageFragment.kt
  app/src/main/res/layout/community_dialog.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: UI, Feat

#71 [LITTLE_FIX]어댑터 코드 조정
  app/src/main/java/com/classic/museo/data/MuseoDTO.kt
  app/src/main/java/com/classic/museo/home/FreeAdapter.kt
  app/src/main/java/com/classic/museo/home/HomeAdapter.kt
  app/src/main/java/com/classic/museo/home/HomeAdapter2.kt
  app/src/main/java/com/classic/museo/home/HomeFragment.kt
  app/src/main/java/com/classic/museo/itemPage/DetailActivity.kt
  app/src/main/java/com/classic/museo/itemPage/search/RegionFragment.kt
  app/src/main/java/com/classic/museo/itemPage/search/SearchAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/search/SearchTabFragment.kt
  app/src/main/res/layout/fragment_community.xml
Labels: LittleFix

#72 [FIX]무료박물관/미술관 버그 긴급 수정
  app/src/main/java/com/classic/museo/home/HomeAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/DetailActivity.kt
Labels: bug

#74 [LITTLE_FIX][BUG]카카오 로그인 커뮤니티 접근, 카카오 로그인 즐겨찾기, 마이페이지 코드 수정
  app/src/main/java/com/classic/museo/data/LikeDTO.kt
  app/src/main/java/com/classic/museo/data/MuseoDTO.kt
  app/src/main/java/com/classic/museo/home/FreeAdapter.kt
  app/src/main/java/com/classic/museo/home/HomeAdapter.kt
  app/src/main/java/com/classic/museo/home/HomeAdapter2.kt
  app/src/main/java/com/classic/museo/home/HomeFragment.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailActivity.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityFragment.kt
  app/src/main/java/com/classic/museo/itemPage/DetailActivity.kt
  app/src/main/java/com/classic/museo/itemPage/MypageInnerActivity/LikeAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/MypageInnerActivity/MypageLike.kt
  app/src/main/java/com/classic/museo/itemPage/search/RegionFragment.kt
  app/src/main/java/com/classic/museo/itemPage/search/SearchAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/search/SearchFragment.kt
  app/src/main/java/com/classic/museo/itemPage/search/SearchTabFragment.kt
Labels: bug, LittleFix

#75 [FIX] : merge시 코드 누락부분 수정
  app/src/main/java/com/classic/museo/home/HomeAdapter2.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityFragment.kt
  app/src/main/java/com/classic/museo/itemPage/MypageFragment.kt
  app/src/main/java/com/classic/museo/itemPage/MypageInnerActivity/MypageLogoutDialog.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_mypage_like_item.xml
Labels: bug

#77 Fix/like 버튼 of/off
  .idea/misc.xml
  app/src/main/java/com/classic/museo/Login/LoginActivity.kt
  app/src/main/java/com/classic/museo/itemPage/DetailActivity.kt
  app/src/main/res/drawable/bookmark.png
  app/src/main/res/drawable/bookmark_push.png
  app/src/main/res/layout/activity_mypage_like_item.xml
Labels: Feat

#81 [FIX] : 🔧: 버튼 UI 크기 조정
  app/src/main/java/com/classic/museo/Login/SignupActivity.kt
  app/src/main/res/drawable/btn_plus.png
  app/src/main/res/drawable/btn_plus.xml
  app/src/main/res/layout/activity_announcement.xml
  app/src/main/res/layout/activity_announcement_detail.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_mypage_like.xml
  app/src/main/res/layout/activity_mypage_written.xml
  app/src/main/res/layout/fragment_community.xml
Labels: UI

#83 [FEAT] : 회원탈퇴 기능
  app/src/main/java/com/classic/museo/itemPage/MypageFragment.kt
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: Feat

#84 [BUG][UI][FEAT]이미지 뷰페이저 기능, 내게시물 버그 수정, 검색 필터 수정, 카카오 회원 즐겨찾기 추가 등
  .idea/misc.xml
  app/src/main/java/com/classic/museo/home/HomeAdapter.kt
  app/src/main/java/com/classic/museo/home/HomeAdapter2.kt
  app/src/main/java/com/classic/museo/home/HomeFragment.kt
  app/src/main/java/com/classic/museo/home/ImageViewPagerAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailActivity.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityFragment.kt
  app/src/main/java/com/classic/museo/itemPage/DetailActivity.kt
  app/src/main/java/com/classic/museo/itemPage/MypageFragment.kt
  app/src/main/java/com/classic/museo/itemPage/MypageInnerActivity/LikeAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/MypageInnerActivity/MypageLike.kt
  app/src/main/java/com/classic/museo/itemPage/MypageInnerActivity/MypageWritten.kt
  app/src/main/java/com/classic/museo/itemPage/search/SearchTabFragment.kt
  app/src/main/res/drawable/image_border.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/image_viewpager_item.xml
  app/src/main/res/layout/recyclerview_item2_big.xml
  app/src/main/res/layout/viewpager_layout.xml
  app/src/main/res/values/strings.xml
Labels: bug, UI, Feat

#85 [FEAT] : 게시물 댓글수 추가(댓글용 png파일 추가), 로그아웃다이얼로그 일부수정. 상세사항 코멘트 참조
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/MypageFragment.kt
  app/src/main/res/drawable/comment.png
  app/src/main/res/layout/activity_mypage_logout_dialog.xml
  app/src/main/res/layout/community_image.xml
Labels: Feat, LittleFix

#86 [HOT_FIX]비회원 정보페이지쪽 코드 오류 수정
  app/src/main/java/com/classic/museo/itemPage/DetailActivity.kt
  app/src/main/java/com/classic/museo/itemPage/MypageFragment.kt
Labels: bug

#88 [UI]스플래쉬화면 수정
  app/src/main/res/drawable/splash_img.png
  app/src/main/res/layout/splash_image.xml
Labels: UI

#91 [BUG][HOTFIX]회원가입 유효성 검사 이메일 부분 수정, 난독화 경고 해결, 아이콘 수정
  app/build.gradle
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/sparta/museo/Login/SignupActivity.kt
  app/src/main/java/com/sparta/museo/itemPage/MypageInnerActivity/MypageWritten.kt
  app/src/main/res/drawable/museologin.png
  app/src/main/res/drawable/museosplash.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/splash_image.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: bug, HOTFIX

#95 게시물 게시할 때 프로그래스바 넣기
  app/src/main/java/com/sparta/museo/itemPage/Community/CommunityDetailActivity.kt
  app/src/main/java/com/sparta/museo/itemPage/Community/CommunityPlusActivity.kt
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/progressbar.xml
Labels: UI, Feat, HOTFIX

#96 [HOTFIX]재배포 및 수정
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sparta/museo/itemPage/Community/CommunityDetailActivity.kt
  app/src/main/java/com/sparta/museo/itemPage/MypageFragment.kt
Labels: HOTFIX

#97 [HOTFIX] 재배포
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/sparta/museo/Login/SignupActivity.kt
  app/src/main/java/com/sparta/museo/itemPage/Community/CommunityDetailActivity.kt
  app/src/main/java/com/sparta/museo/itemPage/Community/CommunityPlusActivity.kt
  app/src/main/java/com/sparta/museo/itemPage/DetailActivity.kt
  app/src/main/java/com/sparta/museo/itemPage/MypageFragment.kt
  app/src/main/java/com/sparta/museo/itemPage/MypageInnerActivity/MypageWritten.kt
  app/src/main/java/com/sparta/museo/retrofit/NetWorkClient.kt
  app/src/main/java/com/sparta/museo/retrofit/NetWorkInterface.kt
  app/src/main/res/drawable/museologin.png
  app/src/main/res/drawable/museosplash.png
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/progressbar.xml
  app/src/main/res/layout/splash_image.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: HOTFIX
