Repository ProjectMuseo/Museo, pull requests merged in 2023-10, with the labels that each got.

#2 UI/login
  .idea/.name
  .idea/compiler.xml
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/androidTest/java/com/classic/museo/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/classic/museo/LoginActivity.kt
  app/src/main/java/com/classic/museo/MainActivity.kt
  app/src/main/res/drawable/kakao_login.png
  app/src/main/res/drawable/login_background.xml
  app/src/main/res/drawable/login_edit.xml
  app/src/main/res/drawable/login_kakao_radius.xml
  app/src/main/res/drawable/museo.png
  app/src/main/res/layout/activity_longin.xml
  app/src/main/res/layout/activity_main.xml
  app/src/test/java/com/classic/museo/ExampleUnitTest.kt
Labels: UI, RENAME, PACK

#3 [DESIGN] : signup page 폴더 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/classic/museo/SignupActivity.kt
  app/src/main/res/layout/activity_signup.xml
Labels: UI

#4 [FEAT] : ⚙️: 메인화면 추가
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/classic/museo/Fragment/CommunityFragment.kt
  app/src/main/java/com/classic/museo/Fragment/HomeFragment.kt
  app/src/main/java/com/classic/museo/Fragment/MypageFragment.kt
  app/src/main/java/com/classic/museo/Fragment/SearchFragment.kt
  app/src/main/java/com/classic/museo/LoginActivity.kt
  app/src/main/java/com/classic/museo/MainActivity.kt
  app/src/main/java/com/classic/museo/ViewPager2Adapter.kt
  app/src/main/res/drawable/community.png
  app/src/main/res/drawable/home.png
  app/src/main/res/drawable/museo.png
  app/src/main/res/drawable/museo.xml
  app/src/main/res/drawable/mypage.png
  app/src/main/res/drawable/search.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/strings.xml
Labels: UI

#7 [API][FEAT][PACK][UI] 카카오 로그인 API
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/classic/museo/LoginActivity.kt
  app/src/main/res/drawable/login_background.xml
  app/src/main/res/drawable/login_kakao_radius.xml
  app/src/main/res/layout/activity_login.xml
  settings.gradle
Labels: UI, PACK, API, Feat

#9 [DESIGN] : signup page UI, [FEAT] : signup page 비밀번호 유효성 검사 기능
  .idea/misc.xml
  app/src/main/java/com/classic/museo/LoginActivity.kt
  app/src/main/java/com/classic/museo/SignupActivity.kt
  app/src/main/res/layout/activity_signup.xml
Labels: UI, Feat

#10 [FEAT] : Login,Signup 수정, MainActivity,MypageFragment일부 수정. 상세사항 코멘트 참조
  app/src/main/java/com/classic/museo/Fragment/MypageFragment.kt
  app/src/main/java/com/classic/museo/LoginActivity.kt
  app/src/main/java/com/classic/museo/MainActivity.kt
  app/src/main/java/com/classic/museo/SignupActivity.kt
  app/src/main/res/drawable/button_background.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: UI, Feat

#14 [DESIGN] : search page UI
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_image.xml
Labels: UI

#18 [FEAT] : MypageFragment 로그아웃 기능 및 작성글, 좋아요 체크 한 글 이동 기능추가 상세사항 코멘트참조
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/classic/museo/Fragment/MypageFragment.kt
  app/src/main/java/com/classic/museo/Fragment/MypageInnerActivity/MypageLike.kt
  app/src/main/java/com/classic/museo/Fragment/MypageInnerActivity/MypageLogoutDialog.kt
  app/src/main/java/com/classic/museo/Fragment/MypageInnerActivity/MypageWritten.kt
  app/src/main/java/com/classic/museo/MainActivity.kt
  app/src/main/java/com/classic/museo/ViewPager2Adapter.kt
  app/src/main/res/drawable/logout_icon.png
  app/src/main/res/drawable/mypage_imagesample.png
  app/src/main/res/layout/activity_mypage_like.xml
  app/src/main/res/layout/activity_mypage_logout_dialog.xml
  app/src/main/res/layout/activity_mypage_written.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: UI, Feat

#21 Feature/detail
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/classic/museo/Fragment/DetailActivity.kt
  app/src/main/java/com/classic/museo/Fragment/HomeFragment.kt
  app/src/main/java/com/classic/museo/Fragment/MypageInnerActivity/MypageLike.kt
  app/src/main/java/com/classic/museo/Fragment/MypageInnerActivity/MypageWritten.kt
  app/src/main/java/com/classic/museo/LoginActivity.kt
  app/src/main/java/com/classic/museo/retrofit/NetWorkClient.kt
  app/src/main/res/drawable/address.png
  app/src/main/res/drawable/back.xml
  app/src/main/res/drawable/border.xml
  app/src/main/res/drawable/like.png
  app/src/main/res/drawable/number.png
  app/src/main/res/drawable/share.png
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_login.xml
Labels: UI

#22 [FEAT] : ⚙️: 카카오 맵 api
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle
  app/libs/libDaumMapAndroid.jar
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/classic/museo/Fragment/DetailActivity.kt
  app/src/main/java/com/classic/museo/LoginActivity.kt
  app/src/main/jniLibs/arm64-v8a/libDaumMapEngineApi.so
  app/src/main/jniLibs/armeabi-v7a/libDaumMapEngineApi.so
  app/src/main/jniLibs/armeabi/libDaumMapEngineApi.so
  app/src/main/res/drawable/like.png
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_login.xml
  settings.gradle
Labels: API, Feat

#23 [FEAT] : [FIX] : [DESIGN] : 상세내역 코멘트 참조
  app/src/main/java/com/classic/museo/Fragment/MypageFragment.kt
  app/src/main/java/com/classic/museo/Fragment/MypageInnerActivity/DummyItem.kt
  app/src/main/java/com/classic/museo/Fragment/MypageInnerActivity/LikeAdapter.kt
  app/src/main/java/com/classic/museo/Fragment/MypageInnerActivity/MypageLike.kt
  app/src/main/java/com/classic/museo/Fragment/MypageInnerActivity/MypageWritten.kt
  app/src/main/java/com/classic/museo/Fragment/MypageInnerActivity/WrittenAdapter.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_mypage_dummyitem.xml
  app/src/main/res/layout/activity_mypage_like.xml
  app/src/main/res/layout/activity_mypage_written.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: bug, UI, Feat

#24 [DESIGN] : [FEAT] : 상세내역 코멘트 참조
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/classic/museo/CommunityDetailActivity.kt
  app/src/main/java/com/classic/museo/CommunityDetailItem.kt
  app/src/main/java/com/classic/museo/Fragment/MypageFragment.kt
  app/src/main/res/drawable/front.png
  app/src/main/res/drawable/mypage_imagesample.png
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_detail_item.xml
  app/src/main/res/layout/activity_mypage_like.xml
  app/src/main/res/layout/activity_mypage_written.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: UI

#25 [FEAT] : ⚙️: Firstor에 회원정보 입력 기능 추가
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/classic/museo/Fragment/MypageFragment.kt
  app/src/main/java/com/classic/museo/ItemPage/Community/CommunityDetailActivity.kt
  app/src/main/java/com/classic/museo/ItemPage/Community/CommunityDetailItem.kt
  app/src/main/java/com/classic/museo/ItemPage/Community/CommunityPlusActivity.kt
  app/src/main/java/com/classic/museo/ItemPage/CommunityFragment.kt
  app/src/main/java/com/classic/museo/ItemPage/DetailActivity.kt
  app/src/main/java/com/classic/museo/ItemPage/HomeFragment.kt
  app/src/main/java/com/classic/museo/ItemPage/MypageFragment.kt
  app/src/main/java/com/classic/museo/ItemPage/MypageInnerActivity/DummyItem.kt
  app/src/main/java/com/classic/museo/ItemPage/MypageInnerActivity/LikeAdapter.kt
  app/src/main/java/com/classic/museo/ItemPage/MypageInnerActivity/MypageLike.kt
  app/src/main/java/com/classic/museo/ItemPage/MypageInnerActivity/MypageLogoutDialog.kt
  app/src/main/java/com/classic/museo/ItemPage/MypageInnerActivity/MypageWritten.kt
  app/src/main/java/com/classic/museo/ItemPage/MypageInnerActivity/WrittenAdapter.kt
  app/src/main/java/com/classic/museo/ItemPage/SearchFragment.kt
  app/src/main/java/com/classic/museo/Login/LoginActivity.kt
  app/src/main/java/com/classic/museo/Login/SignupActivity.kt
  app/src/main/java/com/classic/museo/MainActivity.kt
  app/src/main/java/com/classic/museo/data/Users.kt
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_plus.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_mypage_like.xml
  app/src/main/res/layout/activity_mypage_written.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_search.xml
Labels: UI, API, Feat

#27 Feature/community
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/classic/museo/MainActivity.kt
  app/src/main/java/com/classic/museo/data/CommunityDTO.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityFragment.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityPlusActivity.kt
  app/src/main/java/com/classic/museo/itemPage/CommunityFragment.kt
  app/src/main/res/drawable/community_comment_edit.png
  app/src/main/res/layout/activity_community_plus.xml
  app/src/main/res/layout/community_detail_image.xml
  app/src/main/res/layout/community_image.xml
  app/src/main/res/layout/fragment_community.xml
Labels: UI, Feat

#28 [FEAT] : ⚙️: 디테일 페이지 데이터 받아오기
  .idea/misc.xml
  app/src/main/java/com/classic/museo/MainActivity.kt
  app/src/main/java/com/classic/museo/itemPage/DetailActivity.kt
Labels: Feat

#30 [DB][BUG]파이어스토어 쿼리로 DB작업 및 지역별 검색 수정
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/classic/museo/MainActivity.kt
  app/src/main/java/com/classic/museo/home/FreeAdapter.kt
  app/src/main/java/com/classic/museo/home/HomeAdapter.kt
  app/src/main/java/com/classic/museo/home/HomeAdapter2.kt
  app/src/main/java/com/classic/museo/home/HomeFragment.kt
  app/src/main/java/com/classic/museo/itemPage/SearchFragment.kt
  app/src/main/java/com/classic/museo/itemPage/search/SearchAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/search/SearchFragment.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/recyclerview_item1.xml
  app/src/main/res/layout/recyclerview_item2_big.xml
  app/src/main/res/layout/search_image.xml
  build.gradle
Labels: bug, DB

#32 [DB][LITTLE_FIX]지역별 검색 수정
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/classic/museo/home/FreeAdapter.kt
  app/src/main/java/com/classic/museo/home/HomeAdapter.kt
  app/src/main/java/com/classic/museo/home/HomeAdapter2.kt
  app/src/main/java/com/classic/museo/home/HomeFragment.kt
  app/src/main/java/com/classic/museo/itemPage/search/SearchAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/search/SearchFragment.kt
  app/src/main/res/layout/recyclerview_item2.xml
  app/src/main/res/layout/search_image.xml
Labels: DB, LittleFix

#33 [FEAT] : ⚙️: 탭 레이아웃 추가
  app/build.gradle
  app/src/main/java/com/classic/museo/MainActivity.kt
  app/src/main/java/com/classic/museo/ViewPager2Adapter.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/navigation/navigation.xml
  settings.gradle
Labels: PACK, Feat

#34 [FEAT] : 커뮤니티 디테일 댓글기능 추가(수정 및 삭제기능 미구현)
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailActivity.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailDataClass.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailListAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/MypageFragment.kt
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_detail_item.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: Feat

#35 Feature/community
  .idea/misc.xml
  app/src/main/java/com/classic/museo/home/HomeFragment.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailActivity.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityFragment.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityPlusActivity.kt
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/community_image.xml
Labels: Feat

#36 [FEATURE] 커뮤니티 컴색 필터 완료, 카카오 로그인 후 게시글 작성까지 완료
  .idea/misc.xml
  app/src/main/java/com/classic/museo/Login/LoginActivity.kt
  app/src/main/java/com/classic/museo/data/KakaoUsers.kt
  app/src/main/java/com/classic/museo/data/Users.kt
  app/src/main/java/com/classic/museo/home/HomeFragment.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailActivity.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityFragment.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityPlusActivity.kt
  app/src/main/res/layout/activity_community_plus.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/community_image.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/values/strings.xml
Labels: Feat

#38 [FEAT] : ⚙️: 디자인 수정
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/classic/museo/home/HomeAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/DetailActivity.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_search.xml
Labels: UI, Feat

#39 [FEAT][LITTLE_FIX]카카오 로그인 게시판 글쓰기 완료, 로그아웃 완료
  app/build.gradle
  app/src/main/java/com/classic/museo/data/CommunityDTO.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailActivity.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityFragment.kt
  app/src/main/java/com/classic/museo/itemPage/MypageInnerActivity/MypageLogoutDialog.kt
Labels: Feat

#43 [FIX] : 🔧: UI수정
  app/src/main/java/com/classic/museo/itemPage/MypageFragment.kt
  app/src/main/res/drawable/btn_plus.xml
  app/src/main/res/drawable/community_img_cycle.xml
  app/src/main/res/font/suite_bold.ttf
  app/src/main/res/font/suite_extrabold.ttf
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_plus.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/themes.xml
Labels: UI

#45 [Bug][Feat][LittleFix][Ui] 스플래시 화면, 카카오 프로필 사진 가져오기 및 버그 수정
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/classic/museo/Login/LoginActivity.kt
  app/src/main/java/com/classic/museo/SplashActivity.kt
  app/src/main/java/com/classic/museo/home/HomeAdapter.kt
  app/src/main/java/com/classic/museo/home/HomeFragment.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailActivity.kt
  app/src/main/java/com/classic/museo/itemPage/MypageFragment.kt
  app/src/main/res/drawable/baseline_account_circle_24.xml
  app/src/main/res/drawable/dari1.jpeg
  app/src/main/res/drawable/dari2.JPG
  app/src/main/res/drawable/dari3.jpeg
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/recyclerview_item2.xml
  app/src/main/res/layout/recyclerview_item_filter.xml
  app/src/main/res/layout/splash_image.xml
Labels: bug, UI, Feat, LittleFix

#47 [FEAT] : 로그인 정보 기억하기 기능 추가(자동로그인은 미구현)
  app/src/main/java/com/classic/museo/Login/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
Labels: UI, Feat

#51 [FIX] : community 게시글 수정 & 삭제 오류 해결
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailActivity.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityEditActivity.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityFragment.kt
  app/src/main/res/drawable/community_deatil_comment.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_edit.xml
Labels: bug, UI

#53 [FEAT][BUG][UI]내 게시물, 검색UI수정, 메인페이지 미술관 아이콘 수정, 무료박물관/미술관 버그 수정
  app/src/main/java/com/classic/museo/home/FreeAdapter.kt
  app/src/main/java/com/classic/museo/home/HomeAdapter.kt
  app/src/main/java/com/classic/museo/home/HomeFragment.kt
  app/src/main/java/com/classic/museo/itemPage/Community/CommunityDetailItem.kt
  app/src/main/java/com/classic/museo/itemPage/MypageInnerActivity/LikeAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/MypageInnerActivity/MypageWritten.kt
  app/src/main/java/com/classic/museo/itemPage/MypageInnerActivity/WrittenAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/search/SearchAdapter.kt
  app/src/main/java/com/classic/museo/itemPage/search/SearchFragment.kt
  app/src/main/res/drawable/drawing.png
  app/src/main/res/drawable/mapicon.png
  app/src/main/res/drawable/search.png
  app/src/main/res/drawable/search.xml
  app/src/main/res/layout/activity_mypage_written.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/mypost_item.xml
  app/src/main/res/layout/recyclerview_free.xml
  app/src/main/res/layout/recyclerview_item_filter.xml
  app/src/main/res/layout/search_image.xml
Labels: bug, UI, Feat
